Android layout
Anna-Timoshenko/Hello pull request #1
Opened 2021-09-24 14:46 UTC by Anna-Timoshenko

2021-09-28 07:56 UTC, TimofeyBurak requested changes

2021-09-28 07:56 UTC, TimofeyBurak commented on HelloDroid/Views/NavigationActivity.cs
> +    class NavigationActivity : ActivityBase<NavigationViewModel>
Access modifier is missing

2021-09-28 07:56 UTC, TimofeyBurak commented on Hello/ViewModels/NavigationViewModel.cs
> +            //Items.AddRangeToGroups<(Category Header, CommandAction Item)>(actions , x => x.Header.ToString(), x => x.Item);
Commented code should not be commited

2021-09-28 11:26 UTC, Anna-Timoshenko commented on HelloDroid/Views/NavigationActivity.cs
> +    class NavigationActivity : ActivityBase<NavigationViewModel>
fixed

2021-09-28 11:26 UTC, Anna-Timoshenko commented on Hello/ViewModels/NavigationViewModel.cs
> +            //Items.AddRangeToGroups<(Category Header, CommandAction Item)>(actions , x => x.Header.ToString(), x => x.Item);
fixed

2021-09-29 07:36 UTC, TimofeyBurak approved these changes

2021-09-29 07:37 UTC, merged